### PR TITLE
Update velocity correctly

### PR DESCRIPTION
**Pull request by lennonhill**

### CODE REVIEW

**Comment by athas** [comment]
This is a port of an Accelerate example [which seems to do the same thing](https://github.com/AccelerateHS/accelerate-examples/blob/master/examples/n-body/Common/World.hs#L32-L42).  Am I misreading the Accelerate code here?

**Comment by lennonhill** [comment]
I think you are right. Perhaps both are incorrect? My point is reflected in the documentation, which seems to deviate from the application (both before and after https://github.com/AccelerateHS/accelerate-examples/commit/bd0f6f09b6bb86fa4980f35915413cdfca5426c1).

**Comment by athas** [comment]
That's certainly possible.  If Accelerate ever fixes this, we will too, but it's more important that these ports match the upstream algorithm, than actually computing something physically meaningful.  (Although that's mostly on principle this time, as I can't imagine this multiplication has any impact on performance.)

**Comment by lennonhill** [comment]
2.5 months later they did: https://github.com/AccelerateHS/accelerate-examples/pull/8

**Pull request merged**
